# Generated by Django 2.0.5 on 2018-05-07 03:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20180504_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to=''),
        ),
    ]
